                                                                                                                                     # views.py
                                                                                                                                     from django.shortcuts import render

                                                                                                                                     def menu(request):
                                                                                                                                         menu_items = [
                                                                                                                                                 {"name": "Burger", "price": 10.99, "description": "A juicy beef burger"},
                                                                                                                                                         {"name": "Pizza", "price": 14.99, "description": "A delicious margherita pizza"},
                                                                                                                                                                 {"name": "Salad", "price": 8.99, "description": "A fresh mix of greens and veggies"},
                                                                                                                                                                         {"name": "Sandwich", "price": 9.99, "description": "A tasty sandwich with your choice of filling"},
                                                                                                                                                                             ]
                                                                                                                                                                                 return render(request, 'menu.html', {'menu_items': menu_items})